default: &default
  adapter: <%= ENV.fetch('DB_ADAPTER', 'postgresql') %>
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  timeout: 5000
  database: <%= ENV.fetch('DB', 'volodymyr_chernikov_base') %>
  reconnect: true

development:
  <<: *default

test:
  <<: *default
  database: 'volodymyr_chernikov_test'
